name: sb_converter
description: A sing-box converter command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.12.0

# Add regular dependencies here.
dependencies:
  dart_mappable: ^4.8.0
  dio: ^5.9.2
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_runner: ^2.15.0
  dart_mappable_builder: ^4.8.0
